project_id: terraform-project-484318
region: asia-south1
zone: asia-south1-a

instance:
  machine_type: e2-standard-4
  disk_size: 50
  data_disk_size: 100
  image: projects/centos-cloud/global/images/family/centos-stream-9

db:
  type: postgres  
  version: "15"
  name: AMDEVDB
  memory_mb: 2048
